version: '1'
services:
  nodejs:
    image: node:22
    container_name: nodejs-app
    working_dir: /app
    volumes:
      - .:/app
    command: ['npm', 'run', 'start']
    ports:
      - '3000:3000'
    networks:
      - backend

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - backend
